{{- $namespace := .Release.Namespace }}
{{- $serviceType := .Values.service.type }}
{{- $servicePort := .Values.service.port }}
{{- $release := .Release.Name }}
{{- range .Values.configuration }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .service }}
  namespace: {{ $namespace }}
  labels:
    app: {{ .service }}
spec:
  type: {{ $serviceType }}
  ports:
    - port: {{ $servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .service }}

---
{{- end }}
