{{- $namespace := .Release.Namespace }}
{{- $pullPolicy := .Values.pullPolicy -}}
{{- $servicePort := .Values.service.port -}}
{{- $replicaCount := .Values.replicaCount -}}
{{- $isAutoscalingEnabled := .Values.global.isAutoscalingEnabled}}
{{- $nodepool := .Values.global.nodepool}}
{{- $version := .Chart.AppVersion -}}
{{- $release := .Release.Name }}
{{- range .Values.configuration }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .service }}
  namespace: {{ $namespace }}
spec:
  replicas: {{ .replicaCount | default $replicaCount }}
  selector:
    matchLabels:
      app: {{ .service }}
  template:
    metadata:
      labels:
        app: {{ .service }}
        aadpodidbinding: osdu-identity
    spec:
{{- if $isAutoscalingEnabled }}
      nodeSelector:
        nodepool: {{ $nodepool }}
{{- end }}      
      volumes:
      {{- if .keyvault }}
        - name: azure-keyvault
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-keyvault
      {{- end }}
      {{- range .pvc }}
        - name: {{ .volume }}
          persistentVolumeClaim:
            claimName: {{ .name }}-pvc
      {{- end }}
      containers:
        - name: {{ .service }}
          image: {{ .repository }}:{{ .tag | default $version }}
          imagePullPolicy: {{ $pullPolicy | default "Always" }}
          ports:
            - name: http
              containerPort: {{ $servicePort }}
              protocol: TCP
          {{- if .probe }}
          readinessProbe:
            httpGet:
              path: {{ .probe }}
              port: http
            initialDelaySeconds: 20
          {{- end }}
          resources:
          {{- if .request }}
            requests:
              cpu: {{ .request.cpu | quote }}
          {{- end }}
          {{- if .limit }}
            limits:
              cpu: {{ .limit.cpu | quote }}
          {{- end }}
          volumeMounts:
          {{- if .keyvault }}
          - name: azure-keyvault
            mountPath: "/mnt/azure-keyvault"
            readOnly: true
          {{- end }}
          {{- range .mount }}
          - name: {{ .name }}
            mountPath: {{ .path }}
          {{- end }}
          {{- if .env }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              {{- if .value }}
              {{- $v := .value }}
              value: {{ tpl ($v | quote) $ }}
              {{- end }}
              {{- if .config }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .config.name }}
                  key: {{ .config.key | quote }}
              {{- end }}
              {{- if .secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secret.name | quote }}
                  key: {{ .secret.key | quote }}
              {{- end }}
            {{- end }}
          {{- end }}

---
{{- end }}
