{{- $namespace := .Release.Namespace }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-processor
  namespace: {{ $namespace }}
  labels:
    app: log-processor
spec:
  selector:
    matchLabels:
      app: log-processor
  template:
    metadata:
      labels:
        app: log-processor
        aadpodidbinding: "osdu-identity"
    spec:
      containers:
      - name: log-processor
        image: {{ .Values.image.repository }}/airflow-function:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        env:
          - name: AzureFunctionsJobHost__functions__0
            value: queueTrigger
          - name: FUNCTIONS_WORKER_RUNTIME
            value: dotnet
          - name: AzureLogWorkspaceLogName
            value: airflow_dag
          - name: AzureLogWorkspaceCustomerId
            valueFrom:
              secretKeyRef:
                name: central-logging
                key: workspace-id
          - name: AzureLogWorkspaceSharedKey
            valueFrom:
              secretKeyRef:
                name: central-logging
                key: workspace-key
          - name: AzureWebJobsStorage
            valueFrom:
              secretKeyRef:
                name: airflow
                key: storage-connection
