---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default-service
  namespace: osdu-azure
spec:
  values:
    ingress:
      dns: osdu-self-dplhacb-d5uy-gw.centralus.cloudapp.azure.com
    configuration:
    - service: default
      repository: neilpeterson/aks-helloworld
      tag: v1
      path: /*
      replicaCount: 1
      env:
      - name: TITLE
        value: "Self Managed OSDU - (v0.11)"
