---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: search-service
  namespace: osdu-azure
spec:
  values:
    ingress:
      dns: osdu-self-dplcedah-7mah-gw.centralus.cloudapp.azure.com
    configuration:
    - service: search
      repository: msosdu.azurecr.io/search
      path: /api/search/v2/*
      probe:
        path: /api/search/v2/swagger-ui.html
        port: http
      keyvault: true
      request:
        cpu: 500m
      limit:
        cpu: 1000m
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v2/api-docs"
          - "*/swagger-resources"
          - "*/swagger-ui.html"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "/api/search/v2/swagger-resources/*"
          - "/api/search/v2/webjars/*"
          - "*/actuator/health"
          - "*/health"
          - "*/_ah/**"
      env:
      - name: spring_application_name
        value: search
      - name: server.servlet.contextPath
        value: /api/search/v2/
      - name: server_port
        value: 80
      - name: ACCEPT_HTTP
        value: true
      - name: APPLICATIONINSIGHTS_CONNECTION_STRING
        value: InstrumentationKey=9caa695d-20d0-413a-bf62-0b9666c0579d
      - name: cosmosdb_database
        value: osdu-db
      - name: entitlements_service_endpoint
        value: http://entitlements/api/entitlements/v2
      - name: entitlements_service_api_key
        value: OBSOLETE
      - name: ENVIRONMENT
        value: evt
      - name: LOG_PREFIX
        value: search
      - name: ELASTIC_CACHE_EXPIRATION
        value: 1
      - name: MAX_CACHE_VALUE_SIZE
        value: 60
      - name: search_service_spring_logging_level
        value: debug
      - name: partition_service_endpoint
        value: http://partition/api/partition/v1
      - name: policy_enabled
        value: "false"
      - name: policy_service_endpoint
        value: http://policy/api/policy/v1
      - name: azure_istioauth_enabled
        value: true
      - name: azure_activedirectory_AppIdUri
        value: api://0ef4dfd1-8adf-441b-aae9-ac7026333520"
      - name: KEYVAULT_URI
        config:
          name: osdu-svc-config
          key: ENV_KEYVAULT
      - name: REDIS_DATABASE
        config:
          name: osdu-svc-config
          key: REDIS_DB_SEARCH
      - name: aad_client_id
        secret:
          name: active-directory
          key: application-appid
      - name: appinsights_key
        secret:
          name: central-logging
          key: appinsights
      - name: AZURE_CLIENT_ID
        secret:
          name: active-directory
          key: principal-clientid
      - name: AZURE_CLIENT_SECRET
        secret:
          name: active-directory
          key: principal-clientpassword
      - name: AZURE_TENANT_ID
        secret:
          name: active-directory
          key: tenantid
