---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: storage-service
  namespace: osdu-azure
spec:
  values:
    ingress:
      dns: osdu-self-dplcedah-59t9-gw.centralus.cloudapp.azure.com
    configuration:
    - service: storage
      repository: msosdu.azurecr.io/storage
      path: /api/storage/v2/*
      probe:
        path: /actuator/health
        port: 8081
        liveness:
          delay: 250
          seconds: 10
      keyvault: true
      request:
        cpu: 500m
        memory: 4Gi
      limit:
        cpu: 1000m
        memory: 4Gi
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v2/api-docs"
          - "*/swagger-resources"
          - "*/swagger-ui.html"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "/api/storage/v2/swagger-resources/*"
          - "/api/storage/v2/webjars/*"
          - "*/actuator/health"
          - "*/health"
      env:
      - name: spring_application_name
        value: storage
      - name: server.servlet.contextPath
        value: /api/storage/v2/
      - name: server_port
        value: 80
      - name: ACCEPT_HTTP
        value: true
      - name: cosmosdb_database
        value: osdu-db
      - name: servicebus_topic_name
        value: recordstopic
      - name: legal_servicebus_topic_name
        value: legaltagschangedtopiceg
      - name: legal_servicebus_topic_subscription
        value: eg_sb_legaltagssubscription
      - name: entitlements_service_endpoint
        value: http://entitlements/api/entitlements/v2
      - name: entitlements_service_api_key
        value: "OBSOLETE"
      - name: legal_service_endpoint
        value: http://legal/api/legal/v1
      - name: search_service_endpoint
        value: http://legal/api/legal/v1
      - name: partition_service_endpoint
        value: http://partition/api/partition/v1
      - name: crs_conversion_service_endpoint
        value: http://crs-conversion-service/api/crs/converter/v2
      - name: policy_enabled
        value: "false"
      - name: policy_service_endpoint
        value: http://policy-service/api/policy/v1
      - name: schema_endpoints_disabled
        value: "false"
      - name: azure_istioauth_enabled
        value: true
      - name: azure_activedirectory_AppIdUri
        value: "api://0ef4dfd1-8adf-441b-aae9-ac7026333520"
      - name: azure_paas_podIdentity_isEnabled
        value: "false"
      - name: JAVA_OPTS
        value: "-XX:InitialRAMPercentage=25.0 -XX:MaxRAMPercentage=50.0"
      - name: "SERVER_TOMCAT_MAXTHREADS"
        value: "400"
      - name: "SERVER_TOMCAT_MINSPARETHREADS"
        value: "200"
      - name: KEYVAULT_URI
        config:
          name: osdu-svc-config
          key: ENV_KEYVAULT
      - name: REDIS_DATABASE
        config:
          name: osdu-svc-config
          key: REDIS_DB_STORAGE
      - name: aad_client_id
        secret:
          name: active-directory
          key: application-appid
      - name: appinsights_key
        secret:
          name: central-logging
          key: appinsights
