---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: token-service
  namespace: dev-sample
spec:
  values:
    ingress:
      dns: osdu-self-dplhacb-d5uy-gw.centralus.cloudapp.azure.com
    configuration:
    - service: token
      repository: osduselfcplhacudmgcr.azurecr.io/self-managed-osdu-login
      tag: latest
      path: /login/*
      replicaCount: 1
